<?php

/**
 * BaseBlock
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $name
 * @property string $description
 * @property clob $content
 *
 * @method string getName()        Returns the current record's "name" value
 * @method string getDescription() Returns the current record's "description" value
 * @method clob   getContent()     Returns the current record's "content" value
 * @method Block  setName()        Sets the current record's "name" value
 * @method Block  setDescription() Sets the current record's "description" value
 * @method Block  setContent()     Sets the current record's "content" value
 *
 * @package    si-invest
 * @subpackage model
 * @author     sergk
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBlock extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('block');
    $this->hasColumn('name', 'string', 255, array(
      'type' => 'string',
      'notnull' => true,
      'length' => 255,
    ));
    $this->hasColumn('description', 'string', 255, array(
      'type' => 'string',
      'notnull' => true,
      'length' => 255,
    ));
    $this->hasColumn('content', 'clob', null, array(
      'type' => 'clob',
    ));
  }

  public function setUp()
  {
    parent::setUp();
    $i18n0 = new Doctrine_Template_I18n(array(
      'fields' =>
      array(
        0 => 'content',
      ),
    ));
    $this->actAs($i18n0);
  }
}