<?php

/**
 * BaseInvestor
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $whois
 * @property string $name
 * @property string $project
 * @property string $role
 * @property string $phone
 * @property string $email
 * @property clob $message
 *
 * @method string   getWhois()   Returns the current record's "whois" value
 * @method string   getName()    Returns the current record's "name" value
 * @method string   getProject() Returns the current record's "project" value
 * @method string   getRole()    Returns the current record's "role" value
 * @method string   getPhone()   Returns the current record's "phone" value
 * @method string   getEmail()   Returns the current record's "email" value
 * @method clob     getMessage() Returns the current record's "message" value
 * @method Investor setWhois()   Sets the current record's "whois" value
 * @method Investor setName()    Sets the current record's "name" value
 * @method Investor setProject() Sets the current record's "project" value
 * @method Investor setRole()    Sets the current record's "role" value
 * @method Investor setPhone()   Sets the current record's "phone" value
 * @method Investor setEmail()   Sets the current record's "email" value
 * @method Investor setMessage() Sets the current record's "message" value
 *
 * @package    si-invest
 * @subpackage model
 * @author     sergk
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInvestor extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('investor');
    $this->hasColumn('whois', 'string', 255, array(
      'type' => 'string',
      'notnull' => true,
      'length' => 255,
    ));
    $this->hasColumn('name', 'string', 255, array(
      'type' => 'string',
      'notnull' => true,
      'length' => 255,
    ));
    $this->hasColumn('project', 'string', 255, array(
      'type' => 'string',
      'notnull' => true,
      'length' => 255,
    ));
    $this->hasColumn('role', 'string', 255, array(
      'type' => 'string',
      'notnull' => true,
      'length' => 255,
    ));
    $this->hasColumn('phone', 'string', 255, array(
      'type' => 'string',
      'notnull' => true,
      'length' => 255,
    ));
    $this->hasColumn('email', 'string', 255, array(
      'type' => 'string',
      'notnull' => true,
      'length' => 255,
    ));
    $this->hasColumn('message', 'clob', null, array(
      'type' => 'clob',
    ));
  }

  public function setUp()
  {
    parent::setUp();
    $timestampable0 = new Doctrine_Template_Timestampable();
    $this->actAs($timestampable0);
  }
}