<?php

/**
 * BaseNews
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $name
 * @property clob $annotation
 * @property clob $content
 * @property string $picture
 * @property integer $status
 *
 * @method string  getName()       Returns the current record's "name" value
 * @method clob    getAnnotation() Returns the current record's "annotation" value
 * @method clob    getContent()    Returns the current record's "content" value
 * @method string  getPicture()    Returns the current record's "picture" value
 * @method integer getStatus()     Returns the current record's "status" value
 * @method News    setName()       Sets the current record's "name" value
 * @method News    setAnnotation() Sets the current record's "annotation" value
 * @method News    setContent()    Sets the current record's "content" value
 * @method News    setPicture()    Sets the current record's "picture" value
 * @method News    setStatus()     Sets the current record's "status" value
 *
 * @package    si-invest
 * @subpackage model
 * @author     sergk
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNews extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('news');
    $this->hasColumn('name', 'string', 255, array(
      'type' => 'string',
      'notnull' => true,
      'length' => 255,
    ));
    $this->hasColumn('annotation', 'clob', null, array(
      'type' => 'clob',
    ));
    $this->hasColumn('content', 'clob', null, array(
      'type' => 'clob',
    ));
    $this->hasColumn('picture', 'string', 255, array(
      'type' => 'string',
      'length' => 255,
    ));
    $this->hasColumn('status', 'integer', null, array(
      'type' => 'integer',
    ));
  }

  public function setUp()
  {
    parent::setUp();
    $sluggable0 = new Doctrine_Template_Sluggable(array(
      'fields' =>
      array(
        0 => 'name',
      ),
    ));
    $timestampable0 = new Doctrine_Template_Timestampable();
    $i18n0 = new Doctrine_Template_I18n(array(
      'fields' =>
      array(
        0 => 'name',
        1 => 'annotation',
        2 => 'content',
      ),
    ));
    $this->actAs($sluggable0);
    $this->actAs($timestampable0);
    $this->actAs($i18n0);
  }
}