<?php

/**
 * BaseGallery
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $name
 * @property string $photo
 * @property integer $position
 *
 * @method string  getName()     Returns the current record's "name" value
 * @method string  getPhoto()    Returns the current record's "photo" value
 * @method integer getPosition() Returns the current record's "position" value
 * @method Gallery setName()     Sets the current record's "name" value
 * @method Gallery setPhoto()    Sets the current record's "photo" value
 * @method Gallery setPosition() Sets the current record's "position" value
 *
 * @package    si-invest
 * @subpackage model
 * @author     sergk
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGallery extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('gallery');
    $this->hasColumn('name', 'string', 255, array(
      'type' => 'string',
      'notnull' => true,
      'length' => 255,
    ));
    $this->hasColumn('photo', 'string', 255, array(
      'type' => 'string',
      'notnull' => true,
      'length' => 255,
    ));
    $this->hasColumn('position', 'integer', null, array(
      'type' => 'integer',
    ));
  }

  public function setUp()
  {
    parent::setUp();
    $i18n0 = new Doctrine_Template_I18n(array(
      'fields' =>
      array(
        0 => 'name',
      ),
    ));
    $this->actAs($i18n0);
  }
}