<?php

/**
 * BaseFeedback
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $name
 * @property string $company
 * @property string $phone
 * @property string $email
 * @property clob $message
 *
 * @method string   getName()    Returns the current record's "name" value
 * @method string   getCompany() Returns the current record's "company" value
 * @method string   getPhone()   Returns the current record's "phone" value
 * @method string   getEmail()   Returns the current record's "email" value
 * @method clob     getMessage() Returns the current record's "message" value
 * @method Feedback setName()    Sets the current record's "name" value
 * @method Feedback setCompany() Sets the current record's "company" value
 * @method Feedback setPhone()   Sets the current record's "phone" value
 * @method Feedback setEmail()   Sets the current record's "email" value
 * @method Feedback setMessage() Sets the current record's "message" value
 *
 * @package    si-invest
 * @subpackage model
 * @author     sergk
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFeedback extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('feedback');
    $this->hasColumn('name', 'string', 255, array(
      'type' => 'string',
      'notnull' => true,
      'length' => 255,
    ));
    $this->hasColumn('company', 'string', 255, array(
      'type' => 'string',
      'notnull' => true,
      'length' => 255,
    ));
    $this->hasColumn('phone', 'string', 255, array(
      'type' => 'string',
      'notnull' => true,
      'length' => 255,
    ));
    $this->hasColumn('email', 'string', 255, array(
      'type' => 'string',
      'notnull' => true,
      'length' => 255,
    ));
    $this->hasColumn('message', 'clob', null, array(
      'type' => 'clob',
    ));
  }

  public function setUp()
  {
    parent::setUp();
    $timestampable0 = new Doctrine_Template_Timestampable();
    $this->actAs($timestampable0);
  }
}