<?php

/**
 * BasePage
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $name
 * @property clob $content
 * @property string $title
 * @property clob $keywords
 * @property clob $description
 * @property integer $status
 *
 * @method string  getName()        Returns the current record's "name" value
 * @method clob    getContent()     Returns the current record's "content" value
 * @method string  getTitle()       Returns the current record's "title" value
 * @method clob    getKeywords()    Returns the current record's "keywords" value
 * @method clob    getDescription() Returns the current record's "description" value
 * @method integer getStatus()      Returns the current record's "status" value
 * @method Page    setName()        Sets the current record's "name" value
 * @method Page    setContent()     Sets the current record's "content" value
 * @method Page    setTitle()       Sets the current record's "title" value
 * @method Page    setKeywords()    Sets the current record's "keywords" value
 * @method Page    setDescription() Sets the current record's "description" value
 * @method Page    setStatus()      Sets the current record's "status" value
 *
 * @package    si-invest
 * @subpackage model
 * @author     sergk
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePage extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('page');
    $this->hasColumn('name', 'string', 255, array(
      'type' => 'string',
      'notnull' => true,
      'length' => 255,
    ));
    $this->hasColumn('content', 'clob', null, array(
      'type' => 'clob',
    ));
    $this->hasColumn('title', 'string', 255, array(
      'type' => 'string',
      'length' => 255,
    ));
    $this->hasColumn('keywords', 'clob', null, array(
      'type' => 'clob',
    ));
    $this->hasColumn('description', 'clob', null, array(
      'type' => 'clob',
    ));
    $this->hasColumn('status', 'integer', null, array(
      'type' => 'integer',
    ));
  }

  public function setUp()
  {
    parent::setUp();
    $sluggable0 = new Doctrine_Template_Sluggable(array(
      'fields' =>
      array(
        0 => 'name',
      ),
    ));
    $timestampable0 = new Doctrine_Template_Timestampable();
    $i18n0 = new Doctrine_Template_I18n(array(
      'fields' =>
      array(
        0 => 'name',
        1 => 'content',
        2 => 'title',
        3 => 'keywords',
        4 => 'description',
      ),
    ));
    $this->actAs($sluggable0);
    $this->actAs($timestampable0);
    $this->actAs($i18n0);
  }
}