investor:
  class: sfDoctrineRouteCollection
  options:
    model:                investor
    module:               investor
    prefix_path:          /investor
    column:               id
    with_wildcard_routes: true

feedback:
  class: sfDoctrineRouteCollection
  options:
    model:                Feedback
    module:               feedback
    prefix_path:          /feedback
    column:               id
    with_wildcard_routes: true

block:
  class: sfDoctrineRouteCollection
  options:
    model:                Block
    module:               block
    prefix_path:          /block
    column:               id
    with_wildcard_routes: true

gallery:
  class: sfDoctrineRouteCollection
  options:
    model:                Gallery
    module:               gallery
    prefix_path:          /gallery
    column:               id
    with_wildcard_routes: true

menu:
  class: sfDoctrineRouteCollection
  options:
    model:                Menu
    module:               menu
    prefix_path:          /menu
    column:               id
    with_wildcard_routes: true

page:
  class: sfDoctrineRouteCollection
  options:
    model:                Page
    module:               page
    prefix_path:          /page
    column:               id
    with_wildcard_routes: true

news:
  class: sfDoctrineRouteCollection
  options:
    model:                News
    module:               news
    prefix_path:          /news
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }


# default rules
homepage:
  url:   /
  param: { module: page, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
