<?php

/**
 * BlockTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlockTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object BlockTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Block');
  }
}