<?php

/**
 * GalleryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GalleryTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object GalleryTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Gallery');
  }

  public function doSelectI18n(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();

    $q->leftJoin($rootAlias . '.Translation t')
        ->andWhere('t.lang = ?', 'ru')
        ->orderBy('position ASC');
    return $q;
  }
}