<?php

/**
 * InvestorTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvestorTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object InvestorTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Investor');
  }
}