<?php

/**
 * Page
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    si-invest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Page extends BasePage
{

  public function save(Doctrine_Connection $conn = null)
  {
    if (!$this->isNew())
    {
      $this->setUpdatedAt(date('Y-m-d h:i:s'));
    }

    return parent::save($conn);
  }

  public function getStatusName()
  {
    return $this->status ? 'Неактивно' : 'Активно';
  }
}
