generator:
  class: sfDoctrineGenerator
  param:
    model_class:           News
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          news
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        status_name: {label: "Статус"}
      list:
        object_actions: {_edit: ~, _delete: ~}
        table_method: doSelectI18n
        display: [=name, status_name, created_at, updated_at]
      filter:  ~
      form:
        display:
          "Общие": [picture, status]
<?php foreach (sfConfig::get('app_lang_list') as $lang => $desc): ?>
          "<?php echo $desc ?>": [<?php echo $lang ?>]
<?php endforeach ?>
      edit:    ~
      new:     ~
