<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createForeignKey('sf_guard_forgot_password', 'sf_guard_forgot_password_user_id_sf_guard_user_id', array(
      'name' => 'sf_guard_forgot_password_user_id_sf_guard_user_id',
      'local' => 'user_id',
      'foreign' => 'id',
      'foreignTable' => 'sf_guard_user',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_group_id_sf_guard_group_id', array(
      'name' => 'sf_guard_group_permission_group_id_sf_guard_group_id',
      'local' => 'group_id',
      'foreign' => 'id',
      'foreignTable' => 'sf_guard_group',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_permission_id_sf_guard_permission_id', array(
      'name' => 'sf_guard_group_permission_permission_id_sf_guard_permission_id',
      'local' => 'permission_id',
      'foreign' => 'id',
      'foreignTable' => 'sf_guard_permission',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('sf_guard_remember_key', 'sf_guard_remember_key_user_id_sf_guard_user_id', array(
      'name' => 'sf_guard_remember_key_user_id_sf_guard_user_id',
      'local' => 'user_id',
      'foreign' => 'id',
      'foreignTable' => 'sf_guard_user',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('sf_guard_user_group', 'sf_guard_user_group_user_id_sf_guard_user_id', array(
      'name' => 'sf_guard_user_group_user_id_sf_guard_user_id',
      'local' => 'user_id',
      'foreign' => 'id',
      'foreignTable' => 'sf_guard_user',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('sf_guard_user_group', 'sf_guard_user_group_group_id_sf_guard_group_id', array(
      'name' => 'sf_guard_user_group_group_id_sf_guard_group_id',
      'local' => 'group_id',
      'foreign' => 'id',
      'foreignTable' => 'sf_guard_group',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_user_id_sf_guard_user_id', array(
      'name' => 'sf_guard_user_permission_user_id_sf_guard_user_id',
      'local' => 'user_id',
      'foreign' => 'id',
      'foreignTable' => 'sf_guard_user',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_permission_id_sf_guard_permission_id', array(
      'name' => 'sf_guard_user_permission_permission_id_sf_guard_permission_id',
      'local' => 'permission_id',
      'foreign' => 'id',
      'foreignTable' => 'sf_guard_permission',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('block_translation', 'block_translation_id_block_id', array(
      'name' => 'block_translation_id_block_id',
      'local' => 'id',
      'foreign' => 'id',
      'foreignTable' => 'block',
      'onUpdate' => 'CASCADE',
      'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('gallery_translation', 'gallery_translation_id_gallery_id', array(
      'name' => 'gallery_translation_id_gallery_id',
      'local' => 'id',
      'foreign' => 'id',
      'foreignTable' => 'gallery',
      'onUpdate' => 'CASCADE',
      'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('menu_translation', 'menu_translation_id_menu_id', array(
      'name' => 'menu_translation_id_menu_id',
      'local' => 'id',
      'foreign' => 'id',
      'foreignTable' => 'menu',
      'onUpdate' => 'CASCADE',
      'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('news_translation', 'news_translation_id_news_id', array(
      'name' => 'news_translation_id_news_id',
      'local' => 'id',
      'foreign' => 'id',
      'foreignTable' => 'news',
      'onUpdate' => 'CASCADE',
      'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('page_translation', 'page_translation_id_page_id', array(
      'name' => 'page_translation_id_page_id',
      'local' => 'id',
      'foreign' => 'id',
      'foreignTable' => 'page',
      'onUpdate' => 'CASCADE',
      'onDelete' => 'CASCADE',
    ));
  }

  public function down()
  {
    $this->dropForeignKey('sf_guard_forgot_password', 'sf_guard_forgot_password_user_id_sf_guard_user_id');
    $this->dropForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_group_id_sf_guard_group_id');
    $this->dropForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_permission_id_sf_guard_permission_id');
    $this->dropForeignKey('sf_guard_remember_key', 'sf_guard_remember_key_user_id_sf_guard_user_id');
    $this->dropForeignKey('sf_guard_user_group', 'sf_guard_user_group_user_id_sf_guard_user_id');
    $this->dropForeignKey('sf_guard_user_group', 'sf_guard_user_group_group_id_sf_guard_group_id');
    $this->dropForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_user_id_sf_guard_user_id');
    $this->dropForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_permission_id_sf_guard_permission_id');
    $this->dropForeignKey('block_translation', 'block_translation_id_block_id');
    $this->dropForeignKey('gallery_translation', 'gallery_translation_id_gallery_id');
    $this->dropForeignKey('menu_translation', 'menu_translation_id_menu_id');
    $this->dropForeignKey('news_translation', 'news_translation_id_news_id');
    $this->dropForeignKey('page_translation', 'page_translation_id_page_id');
  }
}