<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addmenu extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable('menu', array(
      'id' =>
      array(
        'type' => 'integer',
        'length' => 8,
        'autoincrement' => true,
        'primary' => true,
      ),
      'url' =>
      array(
        'type' => 'string',
        'notnull' => true,
        'length' => 255,
      ),
      'position' =>
      array(
        'type' => 'integer',
        'length' => 8,
      ),
      'status' =>
      array(
        'type' => 'enum',
        'values' =>
        array(
          0 => 'Активно',
          1 => 'Неактивно',
        ),
        'length' => NULL,
      ),
    ), array(
      'indexes' =>
      array(
      ),
      'primary' =>
      array(
        0 => 'id',
      ),
    ));
  }

  public function down()
  {
    $this->dropTable('menu');
  }
}