<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addgallery extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable('gallery', array(
      'id' =>
      array(
        'type' => 'integer',
        'length' => 8,
        'autoincrement' => true,
        'primary' => true,
      ),
      'photo' =>
      array(
        'type' => 'string',
        'notnull' => true,
        'length' => 255,
      ),
      'position' =>
      array(
        'type' => 'integer',
        'length' => 8,
      ),
    ), array(
      'indexes' =>
      array(
      ),
      'primary' =>
      array(
        0 => 'id',
      ),
    ));
  }

  public function down()
  {
    $this->dropTable('gallery');
  }
}