<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addpagetranslation extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createTable('page_translation', array(
      'id' =>
      array(
        'type' => 'integer',
        'length' => 8,
        'primary' => true,
      ),
      'name' =>
      array(
        'type' => 'string',
        'notnull' => true,
        'length' => 255,
      ),
      'content' =>
      array(
        'type' => 'clob',
        'length' => NULL,
      ),
      'title' =>
      array(
        'type' => 'string',
        'length' => 255,
      ),
      'keywords' =>
      array(
        'type' => 'clob',
        'length' => NULL,
      ),
      'description' =>
      array(
        'type' => 'clob',
        'length' => NULL,
      ),
      'lang' =>
      array(
        'fixed' => true,
        'primary' => true,
        'type' => 'string',
        'length' => 2,
      ),
    ), array(
      'indexes' =>
      array(
      ),
      'primary' =>
      array(
        0 => 'id',
        1 => 'lang',
      ),
    ));
  }

  public function down()
  {
    $this->dropTable('page_translation');
  }
}