generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardPermission
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_permission
    with_doctrine_route:   true

    config:
      list:
        object_actions: {_edit: ~, _delete: ~}
        title: Список разрешений
        display: [=name, description, created_at, updated_at]

      edit:
        title: Редактирования разрешения "%%name%%"

      new:
        title: Новое разрешение

      form:
        display: [name, description, groups_list, users_list]