generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true

    config:
      fields:
        password_again: { label: "Password (again)" }

      list:
        object_actions: {_edit: ~, _delete: ~}
        title:   Список пользователей
        display: [=username, created_at, updated_at, last_login]

      form:
        class: sfGuardUserAdminForm
        display:
          "User":                   [first_name, last_name, email_address, username, password, password_again]
          "Permissions and groups": [is_active, is_super_admin, groups_list, permissions_list]
      edit:
        title: Редактировать пользователя "%%username%%"

      new:
        title: Новый пользователь

      filter:
        display:
          [first_name, last_name, email_address, username, is_active, is_super_admin, groups_list]          